FROM debian:bookworm-slim
WORKDIR /tlink
RUN apt-get update && DEBIAN_FRONTEND=non-interactive apt-get install -qy --no-install-recommends --no-install-suggests \
    iproute2 iptables procps tcpdump iputils-ping nano \
    && rm -rf /var/lib/apt/lists/*
