version: '3.9'

services:
  satellite:
    tty: true
    stdin_open: true
    container_name: satellite
    image: tlink
    command: --config tlink.yaml --logs /tlink/tlink.log
    volumes:
      - ./tlink.yaml:/tlink/tlink.yaml
    privileged: true
    cap_add:
      - NET_ADMIN
    networks:
      st:
        ipv4_address: 10.1.1.254
      gw:
        ipv4_address: 10.2.2.254

  client:
    tty: true
    stdin_open: true
    container_name: client
    image: testbed
    cap_add:
      - NET_ADMIN
    networks:
      st:
        ipv4_address: 10.1.1.2
    command: bash -c "ip route add 10.2.2.0/24 via 10.1.1.254 && bash"

  server:
    tty: true
    stdin_open: true
    container_name: server
    image: testbed
    cap_add:
      - NET_ADMIN
    networks:
      gw:
        ipv4_address: 10.2.2.2
    command: bash -c "ip route add 10.1.1.0/24 via 10.2.2.254 && bash"

networks:
  st:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.1.0/24
  gw:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.2.2.0/24
